Table organizations {
  org_id    serial      [pk, increment]
  orgname   varchar(500) [not null]
  country   char(3)
  town      varchar(100)
  // orgid
}

Table journals {
  journal_id  serial       [pk, increment]
  title       varchar(500) [not null]
  issn        varchar(20)
  eissn       varchar(20)
  publisher   varchar(500)
  country     char(3)
  town        varchar(100)
  vak         boolean
  rsci        boolean
  corerisc    boolean
  wos         boolean
  scopus      boolean
  // сайт
  // префикс DOI
  // переводная версия (ссылка на другой журнал)
}

// добавить journal_titles

Table issues {
  issue_id    serial      [pk, increment]
  journal_id  integer     [not null, ref: > journals.journal_id]
  year        smallint    [not null]
  volume      smallint
  number      varchar(20)
  contnumber  integer
}

Table items {
  item_id     integer     [pk]
  issue_id    integer     [not null, ref: > issues.issue_id]
  linkurl     text
  genre       varchar(100)
  type        varchar(100)
  pages       varchar(30)
  language    char(2)
  doi         varchar(100)
  edn         varchar(20)
  grnti       varchar(20)
  risc        boolean
  corerisc    boolean
  citation    text
  supported   text
  // дата печати
  // дата поступления в редакцию
  // число авторов
  // переводная версия (ссылка на другой item)
}

Table authors {
  author_id           serial       [pk, increment]
  elibrary_author_id  integer      [unique]
  firstname           varchar(200)
  middlename          varchar(200)
  lastname            varchar(200) [not null]
  initials            varchar(200)
  email               varchar(200)
  // general_organization // сделать ссылку на организацию
}

Table item_authors {
  id        serial    [pk, increment]
  item_id   integer   [not null, ref: > items.item_id]
  author_id integer   [not null, ref: > authors.author_id]
  num       smallint
  aboutauthor  varchar(300)
  // кол-во аффиляций

  indexes {
    (item_id, author_id) [unique]
  }
}

Table author_affiliations {
  id             serial   [pk, increment]
  item_author_id integer  [not null, ref: > item_authors.id]
  org_id         integer  [not null, ref: > organizations.org_id]
  num            smallint
  // как автор сам указал аффиляцию (например один пишет НГУ, другой Новосибирский ...)
}

Table titles {
  title_id    serial   [pk, increment]
  item_id     integer  [not null, ref: > items.item_id]
  lang        char(2)
  title_text  text     [not null]
}

Table abstracts { // delete
  abstract_id    serial   [pk, increment]
  item_id        integer  [not null, ref: > items.item_id]
  lang           char(2)
  abstract_text  text
}

Table keywords { // delete
  keyword_id    serial       [pk, increment]
  item_id       integer      [not null, ref: > items.item_id]
  lang          char(2)
  keyword_text  varchar(300)
}

Table codes { // delete
  code_id     serial      [pk, increment]
  item_id     integer     [not null, ref: > items.item_id]
  code_type   varchar(50)
  code_value  varchar(50)
}

Table references { // убрать
  reference_id    serial   [pk, increment]
  item_id         integer  [not null, ref: > items.item_id]
  num             smallint
  reference_text  text
}

Table white_list_versions {
  version_id   serial      [pk, increment]
  version_name varchar(100) [not null]
  published_at date
  description  text
}

Table white_list_entries {
  entry_id    serial   [pk, increment]
  journal_id  integer  [not null, ref: > journals.journal_id]
  version_id  integer  [not null, ref: > white_list_versions.version_id]
  level       smallint
  included_at date
  excluded_at date

  indexes {
    (journal_id, version_id) [unique]
  }
}

// добавить таблицу organization_names (org_id, name, type)

// добавить таблицу author_names

// добавить vak
// rsci
// corerisc
// risc
// wos
// scopus
// white_list
// у каждой бд (имя, сайт, префикс квартиля)

// у таблицы db @ journals (год, входит или нет, квартиль, if(float), процентиль(float))

// добавить db @ authours (id в базе данных (text))
